service: yoga-example

plugins:
  - serverless-offline
  - serverless-plugin-optimize

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs6.10

functions:
  graphql:
    handler: handler.server
    events:
      - http:
          path: /
          method: post
          cors: true
  playground:
    handler: handler.playground
    events:
      - http:
          path: /
          method: get
          cors: true

package:
  individually: true
